//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDB_tbl
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Salary { get; set; }
        public Nullable<int> Employee_Mobile { get; set; }
    }
}
